apiVersion: v1
kind: Service
metadata:
  name: hana-news-api
  namespace: hana-securities
  labels:
    app: hana-news-api
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  selector:
    app: hana-news-api
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
